config/routes.rb
Masuknegeriv2::Application.routes.draw do

  devise_for :students, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'},
    :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

  devise_for :contributors

  devise_for :admins

  resources :subjects
  resources :contributors
  resources :questions
  resources :exams

  root :to => 'home#index'

end

app/models/exam.rb
class Exam
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :type, type: String
  field :date, type: Date
  field :start_time, type: DateTime
  field :finish_time, type: DateTime
  field :description, type: String
  field :akbar, type:Boolean, default:true #akbar

  has_many :questions
  belongs_to :program

  default_scope desc(:date)

  TYPE = {
  	"smptn" => {correct:4, wrong:-1, unanswered:0},
  	"un" => {correct:1, wrong:-1, unanswered:0},
    "mandiri" => {correct:4, wrong:-1, unanswered:0}
  }

  validates_presence_of :type, :program_id, :start_time, :finish_time
  validates_inclusion_of :type, :in => Exam::TYPE.keys

  def un?
  	self.type.eql?("un")
  end

  def smptn?
  	self.type.eql?("smptn")
  end

  def mandiri?
    self.type.eql?("mandiri")
  end

  def active?
    (Time.now >= self.start_time) && (Time.now <= self.finish_time)
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
  end

  def edit
  end

  def new
  	@exam = Exam.new
  end

  def show
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_dashboard.html.haml
%nav#support-nav
  %ul
    %li= link_to "Daftar Tryout Akbar", exams_path
    %li= link_to "Daftar Tryout Akbar SMPTN", exams_path(type:'smptn')
    %li= link_to "Daftar Tryout Akbar UN", exams_path(type:'un')
    %li= link_to "Tambah Exam Akbar", new_exam_path

app/views/exams/_form.html.haml
= simple_form_for @exam, :html => {:class => "globalForm"} do |f|
  = f.input :name
  = f.input :type
  = f.input :date
  = f.input :start_time
  = f.input :finish_time
  = f.submit "Simpan"

app/views/exams/edit.html.haml
%h1 Exams#edit
%p Find me in app/views/exams/edit.html.haml

app/views/exams/index.html.haml
= render 'dashboard'

app/views/exams/new.html.haml
%h1 Buat Exam Akbar
= render "form"

app/views/exams/show.html.haml
%h1 Exams#show
%p Find me in app/views/exams/show.html.haml