config/routes.rb
Masuknegeriv2::Application.routes.draw do

  devise_for :students, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'},
    :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

  devise_for :contributors

  devise_for :admins

  resources :subjects
  resources :contributors
  resources :questions
  resources :exams

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_credential.html.haml
%nav#support-nav
  %ul
    - if student_signed_in?
      %li= "Hi, #{current_student.name}!"
      %li= link_to "List Badges", "#"
      %li= link_to "Logout", destroy_student_session_path, :method => :delete
    - else
      %li= link_to "Home", root_path
      %li= link_to "About masuknegeri.com", "#"
      %li= link_to "About edulab", "#"
      %li= link_to "Other"


%nav{id:"main-nav", role:"navigation"}
  %ul
    - if student_signed_in?
      %li= link_to "Dashboard", "#"
      %li= link_to "Latihan", subjects_path
      %li= link_to "Tryout", "#"
      %li.last-list= link_to "Rekor", "#"
    - elsif contributor_signed_in?
      %li= link_to "Home", root_path
      %li= link_to "Soal Latihan", "#"
      %li= link_to "Soal Tryout", "#"
      %li= link_to "Laporan Soal", "#"
      %li= link_to "Upload"
      %li.last-list= link_to "Logout", destroy_contributor_session_path, :method => :delete
    - elsif admin_signed_in?
      %li= link_to "Home", root_path
      %li= link_to "Artikel", "#"
      %li= link_to "Student", "#"
      %li= link_to "Contributor", "#"
      %li= link_to "School", "#"
      %li.last-list= link_to "Logout", destroy_admin_session_path,  :method => :delete
    - else
      %li= link_to "Login", new_student_session_path
      %li.last-list= link_to "Register", new_student_registration_path