config/routes.rb
Masuknegeriv2::Application.routes.draw do

  devise_for :students, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register'},
    :controllers => {:omniauth_callbacks => "omniauth_callbacks"}

  devise_for :contributors

  devise_for :admins

  resources :subjects
  resources :contributors
  resources :questions
  resources :exams

  root :to => 'home#index'

end

app/models/contributor.rb
class Contributor
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable#:registerable, :recoverable, :rememberable, :trackable, :validatable
  field :name
  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  has_many :questions

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  before_filter :authenticate_admin!
  
  def index
    @contributors = Contributor.all.page(params[:page]).per(15)
  end

  def edit
  end

  def show
  end

  def new
  	@contributor = Contributor.new
  end

  def create
    @contributor = Contributor.new(params[:contributor])
    if @contributor.save
      redirect_to contributors_path, :notice => "Kontributor berhasil dibuat."
    else
      render "new"
    end
  end

  def update
    @contributor = Contributor.find params[:id]
    if @contributor.update_attributes(params[:contributor])
      redirect_to @contributor, :notice => "kontributor berhasil di-update."
    else
      render "edit"
    end
  end

  def edit
    @contributor = Contributor.find params[:id]
  end

  def destroy
    @contributor = Contributor.find params[:id]
    @contributor.destroy
    redirect_to contributors_path
  end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/_form.html.haml
= simple_form_for @contributor, :html => {:class => "globalForm"} do |f|
  = f.input :name
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.submit "Simpan"

app/views/contributors/edit.html.haml
%h1 Contributors#edit
%p Find me in app/views/contributors/edit.html.haml

app/views/contributors/index.html.haml
#primary.grid_16
  %h2
    Contributors list
  %nav.adminSubMenu
    =link_to "Tambah contributor", new_contributor_path
  = page_entries_info @contributors
  %table.adminTable
    %tr
      %th
        Nama
      %th
        Email
      %th
        Jumlah Soal
      %th.option{:colspan => "2"}
        Pilihan
    - @contributors.each do |contributor|
      %tr
        %td
          = link_to contributor.name, contributor_path(contributor)
        %td
          = contributor.email
        %td
          = contributor.questions.count
        %td
          = link_to "Edit", edit_contributor_path(contributor)
        %td
          = link_to "Delete", contributor_path(contributor), :method => :delete, :confirm => "Hapus?"
  = paginate @contributors

app/views/contributors/new.html.haml
#primary.grid_16
  %h2
    Create contributor
  = render "form"

app/views/contributors/show.html.haml
%h1 Contributors#show
%p Find me in app/views/contributors/show.html.haml